<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE beans [
        <!ELEMENT beans (bean*)>
        <!ELEMENT bean (property*)>
        <!ELEMENT property (#PCDATA)>
        <!ATTLIST bean id ID #REQUIRED>
        <!ATTLIST bean class CDATA #IMPLIED>
        <!ATTLIST property name CDATA #IMPLIED>
        <!ATTLIST property ref CDATA #IMPLIED>
        ]>

<beans>

    <bean id="page" class="com.at.myssm.myspringmvc.PageController"></bean>
    <bean id="userService" class="com.app.book.service.Impl.UserServiceImpl">
        <property name="userDAO" ref="userDAO"></property>
    </bean>
    <bean id="userDAO" class="com.app.book.DAO.Impl.UserDAOImpl"></bean>

    <bean id="user" class="com.app.book.controller.UserControllers">
        <property name = "userService" ref = "userService" ></property>
    </bean>



</beans>